inbox/urls.py
from django.conf.urls import patterns, url
from .views import SendMessageAPI, ListMessagesAPI

urlpatterns = patterns(
    '',
    url(r'^api/messages/send/$', SendMessageAPI.as_view(), name="send-message"),
    url(r'^api/applies/(?P<pk>\d+)/messages/$', ListMessagesAPI.as_view(), name="list-messages"),
)

account/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django_hstore import hstore
from services.models import Category, SubCategory, Service, District


class TimeAvailability(models.Model):
    monday_since = models.TimeField(null=True, blank=True)
    monday_to = models.TimeField(null=True, blank=True)
    tuesday_since = models.TimeField(null=True, blank=True)
    tuesday_to = models.TimeField(null=True, blank=True)
    wednesday_since = models.TimeField(null=True, blank=True)
    wednesday_to = models.TimeField(null=True, blank=True)
    thursday_since = models.TimeField(null=True, blank=True)
    thursday_to = models.TimeField(null=True, blank=True)
    friday_since = models.TimeField(null=True, blank=True)
    friday_to = models.TimeField(null=True, blank=True)
    saturday_since = models.TimeField(null=True, blank=True)
    saturday_to = models.TimeField(null=True, blank=True)
    sunday_since = models.TimeField(null=True, blank=True)
    sunday_to = models.TimeField(null=True, blank=True)
    owner = models.OneToOneField(User)


class Profile(models.Model):
    dni = models.CharField(null=True, blank=True, max_length=8)
    district = models.ForeignKey(District, related_name='applicants_from', null=True, blank=True)
    address = models.CharField(max_length=100, blank=True)
    mobile_phone = models.CharField(max_length=11, blank=True)
    home_phone = models.CharField(max_length=11, blank=True)
    other_phones = hstore.DictionaryField(null=True, blank=True)
    user = models.OneToOneField(User)
    photo = models.ImageField(upload_to='users/photos/', null=True, blank=True)
    about_me = models.TextField(blank=True)
    category = models.ForeignKey(Category, null=True, blank=True)
    subcategories = models.ManyToManyField(SubCategory, null=True, blank=True)
    is_applicant = models.BooleanField(default=False)
    is_new = models.BooleanField(default=True)
    allow_districts = models.ManyToManyField(District, related_name='applicants_work', blank=True)
    url_hash = models.CharField(max_length=40, blank=True, db_index=True)
    verified = models.BooleanField(default=True)
    verified_applicant = models.BooleanField(default=True)

    objects = hstore.HStoreManager()

    def create_temporary_link(self):
        self.url_hash = str(uuid.uuid4())

    @property
    def rated_services(self):
        return self.user.done_services.filter(done_score__gt=0).count()

    @property
    def done_services(self):
        return self.user.done_services.filter(done_by=self.user).count()

    def stars_by_subcategory(self, subcategory):
        val = self.user.done_services.filter(subcategory=subcategory).aggregate(Sum('done_score'))['done_score__sum']
        rated_services = self.user.done_services.filter(done_score__gt=0, subcategory=subcategory,
                                                        done_score__isnull=False).count()
        return val / rated_services if val and rated_services else 0

    def last_services(self):
        scs = self.subcategories.values_list('slug', flat=True).all()
        return Service.objects.filter(done_by__isnull=True, subcategory__in=scs).order_by('-created_at')[:5]

    @property
    def photo_url(self):
        return self.photo.url if self.photo else None

    def __unicode__(self):
        return self.user.email


class WorkPhoto(models.Model):
    owner = models.ForeignKey(User, related_name='work_photos')
    image = models.ImageField(upload_to='users/jobs/')
    subcategory = models.ForeignKey(SubCategory, related_name='photos')
    caption = models.TextField(blank=True)

    @property
    def photo_url(self):
        return self.image.url if self.image.url else None

    def __unicode__(self):
        return self.photo_url

templates/activate.html
{% extends "base.html" %}

{% block content %}
    <div>
        <p>Gracias por verificar tu cuenta, ahora puedes loguearte y tener acceso a toda la plataforma.</p>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Pagina para usuarios no Logueados</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/style.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/font-awesome.css"/>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/registro.js"></script>

    {% block js %}{% endblock %}
    {% block css %}{% endblock %}
</head>
<body>
<div class="wrapper">
    <div class="page-wrap">
        <header class="in_header">
            {% block header %}
                <div class="sr_margen">
                    <div class="ih_cont">
                        <div class="sr_logo">
                            <a href="{% url "services:home" %}"><p>Servicioslibre<span>.com</span></p></a>
                        </div>
                        <div class="ih_nav">
                            <ul>
                                <li><a href="#">¿Cómo funciona?</a></li>
                                <li><a href="#">¿Quieres brindar servicios?</a></li>
                                <li><a class="{% block nav_request %}{% endblock %}"
                                       href="{% url 'services:request-service' %}">Solicitar servicio</a></li>
                            </ul>
                        </div>
                        <div class="ih_sesion">
                            <a class="sl-btn ihs_sign" href="{% url "account:register" %}">Registrate</a>
                            <a class="sl-btn ihs_login" href="{% url "account:login" %}">Inicia sesión</a>
                        </div>
                    </div>
                </div>
            {% endblock %}
        </header>
        <section id="main">
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="sr_footer">
        <div class="sr_margen">
            <ul class="btn_social">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            </ul>
            <ul class="srf_select">
                <li><a href="#">Contáctanos</a></li>
                <li><a href="#">Pagos</a></li>
                <li><a href="#">Preguntas más frecuentes</a></li>
                <li><a href="#">Términos y condiciones</a></li>
            </ul>
            <div class="srf_bot">
                <p>© 2016 Servicios Libre</p>

                <p>hecho con ♥ en Lima</p>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="banner1">
        <div class="baner1_cont">
            <div class="sr_margen">
                <div class="title">
                    <p>Necesitas un servicio para tu casa o un evento...</p>

                    <div class="clearfix"></div>
                    <p>aquí encontrarás emprendedores independientes</p>

                    <div class="clearfix"></div>
                    <p>a tu disposición.</p>

                    <div class="clearfix"></div>
                </div>

                <div class="button-trans" onclick="window.location='/request-service/step1/'">Solicita un servicio
                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="pasos">
        <div class="sr_margen">
            <ul>
                <li class="info_cont">
                    <div class="paso paso-der">

                        <!--img src="{{ STATIC_URL }}images/Pasos_Foto1.png" alt="primer-paso" class="paso-img"/-->
                        <div class="number">1</div>

                        <div class="text">
                            <p class="title"><span>Describe</span> el servicio</p>

                            <p class="subtitle">Cuéntanos sobre el servicio que necesitas, dónde, cuándo y el
                                alcance de este.</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </li>
                <!--li class="ag_cont"><img src="{{ STATIC_URL }}images/arrow_green.png" alt=""/></li-->
                <li class="info_cont">
                    <div class="paso paso-izq">

                        <!--img src="{{ STATIC_URL }}images/Pasos_Foto2.png" alt="segundo-paso" class="paso-img"/-->
                        <div class="number">2</div>
                        <div class="text">
                            <p class="title"><span>Elige</span> al indicado</p>

                            <p class="subtitle">Se contactado por emprendedores o recibe nuestras
                                recomendaciones.</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </li>
                <!--li class="ag_cont"><img src="{{ STATIC_URL }}images/arrow_green.png" alt=""/></li-->
                <li class="info_cont">
                    <div class="paso paso-der">
                        <div class="number">3</div>
                        <!--img src="{{ STATIC_URL }}images/Pasos_Foto3.png" alt="tercer-paso" class="paso-img"/-->

                        <div class="text">
                            <p class="title"><span>Paga</span> al final</p>

                            <p class="subtitle">Pagas una vez que el servicio haya sido realizado
                                satisfactoriamente.</p>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <!--div class="banner2"></div-->
    <div class="banner4">
        <div class="sr_margen"><img src="{{ STATIC_URL }}images/plumber.png" alt=""/></div>
    </div>
    <div class="categorias">
        <div class="sr_margen">
            <h1 class="sl-title">Nuestras Categorías</h1>
            <ul class="cat-list">
                <li>
                    <div class="cb_content">
                        <div class="category-box">
                            <img src="{{ STATIC_URL }}images/parties.jpg" alt=""/>
                        </div>
                        <div class="cb_text_c cbt_1">
                            <p>Eventos & Fiestas</p>
                            <img src="{{ STATIC_URL }}images/p_icon.png" alt=""/>
                        </div>

                    </div>
                </li>
                <li>
                    <div class="cb_content">
                        <div class="category-box">
                            <img src="{{ STATIC_URL }}images/bienestar.jpg" alt=""/>
                        </div>
                        <div class="cb_text_c cbt_2">
                            <p>Belleza & Bienestar</p>
                            <img src="{{ STATIC_URL }}images/b_icon.png" alt=""/>
                        </div>

                    </div>
                </li>
                <li>
                    <div class="cb_content">
                        <div class="category-box">
                            <img src="{{ STATIC_URL }}images/private-class.gif" alt=""/>
                        </div>
                        <div class="cb_text_c cbt_4">
                            <p>Clases particulares</p>
                            <img src="{{ STATIC_URL }}images/c_icon.png" alt=""/>
                        </div>

                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html ng-app="suricats">
<head>
    <title></title>
    <script>
        var userid ={{ user.id }};
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/textarea-expander.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-route.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/ng-animate.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-mocks.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/ng-tags-input.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/lodash.underscore.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/restangular.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/autocomplete.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/jquery-ui.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/ngAutocomplete.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-ui-router.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/infinite-scroll.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-resource.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/fileUp.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-cookies.js"></script>

    <link rel="stylesheet" href="{{ STATIC_URL }}styles/style.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/autocomplete.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/font-awesome.css"/>

    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app/suricats.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app/controllers/initializeCtrl.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app/controllers/ac_headerCtrl.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app/controllers/ac_solicitudCtrl.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app/controllers/ac_createCtrl.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app/controllers/ac_chatCtrl.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app/controllers/ac_applicantCtrl.js"></script>
    <!--Google maps api key-->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&sensor=true"></script>
</head>
<body ng-controller="initializeCtrl">
<div class="wrapper">
    <div class="page-wrap">
        <div ui-view="header"></div>
        <div ui-view class="wr_body"></div>
    </div>
    <div ui-view="footer" class="sr_footer"></div>
</div>
</body>
</html>

templates/index_applicant.html
<!DOCTYPE html>
<html data-ng-app="suricats">
<head>
    <title></title>
    <script type="application/javascript">
        var userid ={{ user.id }};
        var verified;
        {% if user.profile.verified %} verified = true;{% else %} verified = false;{% endif %}
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/jquery.autosize.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/textarea-expander.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular.min.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/vendor/app_calendar/jquery-ui/ui/jquery.ui.core.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/vendor/app_calendar/jquery-ui/ui/jquery.ui.widget.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/vendor/app_calendar/jquery-ui/ui/jquery.ui.mouse.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/vendor/app_calendar/jquery-ui/ui/jquery.ui.draggable.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/vendor/app_calendar/jquery-ui/ui/jquery.ui.droppable.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/vendor/app_calendar/jquery-ui/ui/jquery.ui.resizable.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/fullcalendar.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/calendar.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-route.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/ng-animate.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-mocks.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/ng-tags-input.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/lodash.underscore.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/restangular.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/autocomplete.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/ngAutocomplete.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-ui-router.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/infinite-scroll.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-resource.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/fileUp.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/vendor/angular-cookies.js"></script>

    <link rel="stylesheet" href="{{ STATIC_URL }}styles/style.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/font-awesome.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/fullcalendar.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/fullcalendar.print.css" media='print'/>

    <script type="text/javascript" src="{{ STATIC_URL }}scripts/src/app_applicant/suricats.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/initializeCtrl.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/first_stepCtrl.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/headerCtrl.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/homeCtrl.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/profileCtrl.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/requestCtrl.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/chatCtrl.js"></script>
    <script type="text/javascript"
            src="{{ STATIC_URL }}scripts/src/app_applicant/controllers/subcategoryCtrl.js"></script>
</head>
<body ng-controller="initializeCtrl">
<div class="wrapper">
    <!--   Modals   -->
    <div class="back_shadow"></div>

    <div class="modal mod_aply" center>
        <div class="aply_cont">
            <form name="aply_serv">
                <div class="ac_head">
                    <h1>Servicio de [[ modal_data.subcategory ]]</h1>

                    <div class="ac_close" ng-click="ac_init.close_modal()"><i class="fa fa-times"></i></div>
                </div>
                <div class="ac_body">

                    <ul class="acb_details">
                        <li>
                            <p class="f_text">Fecha</p>

                            <p class="l_text st_text"><span data-ng-if="!modal_data.date">Lo más pronto posible</span>[[modal_data.date]]
                            </p>
                        </li>
                        <li data-ng-if="modal_data.hour">
                            <p class="f_text">Hora</p>

                            <p class="l_text st_text">[[modal_data.hour]]
                            </p>
                        </li>
                        <li>
                            <p class="f_text">Dirección</p>

                            <p class="l_text st_text">[[modal_data.address]]</p>
                        </li>
                        <li>
                            <p class="f_text">Descripción</p>

                            <div class="l_text st_text">
                                <p>Me gustaría contar con un servicio de [[modal_data.subcategory]]</p>

                                <p data-ng-if="modal_data.details">para un(a)
                                    <b>[[modal_data.details['event-type'] ]]</b> con
                                    <b>[[modal_data.details['number-people'] ]]</b> invitado(s) y una duración de
                                    <b>[[modal_data.details['duration'] ]]</b> hr(s).
                                </p>
                            </div>
                        </li>
                    </ul>

                    <div class="aply_service" data-ng-show="modal_data.my_apply==null && verified">
                        <h3>Aplica a este servicio</h3>

                        <p>
                            Puedo realizar el servicio por
                            s/.<input ng-class="{true: 'valid_f'}[!state_price]"
                                      name="price" type="number" ng-model="price" placeholder="precio"
                                      required/>
                            <span class="valid_style" ng-if="!state_price">Pon un precio</span>

                        </p>
                        <textarea name="describe" class="i_textarea" ng-model="describe"
                                  placeholder="Agregar detalles"
                                ></textarea>

                    </div>
                </div>
                <div class="ac_bottom" data-ng-show="verified" data-ng-class="{true:'red_aply'}[modal_data.my_apply!=null]">
                    <p class="acb_p" data-ng-show="modal_data.my_apply">
                        Ya aplicaste a este servicio. <a href="" ng-click="ac_init.go_request(modal_data.my_apply)">Ver
                        solicitud</a>
                    </p>
                    <button type="button" class="sl-btn btn_aply" data-ng-show="modal_data.my_apply==null"
                            data-ng-click="ac_init.aplicar(aply_serv,[[modal_data.id]])">Aplicar
                    </button>
                </div>
                <div class="ac_bottom" data-ng-show="!verified" data-ng-class="{true:'red_aply'}[!verified]">
                    <p class="acb_p">
                        Debe ser profesional verificado para poder aplicar aun servicio.
                    </p>
                </div>
            </form>
        </div>
    </div>
    <div class="modal aply_click" center>
        <div class="ac_content">
            <div class="ac_head">
                <h1>Servicio Aplicado</h1>

                <div class="ac_close" ng-click="ac_init.close_modal()"><i class="fa fa-times"></i></div>
            </div>
            <div class="ac_body">
                <p>Propuesta enviada</p>
            </div>
            <div class="ac_bottom">
                <button class="sl-btn btn_aply" ng-click="ac_init.close_modal()">Aceptar</button>
            </div>
        </div>
    </div>
    <!--   Fin de los modals   -->
    <div class="page-wrap">
        <div ui-view="header"></div>
        <div ui-view class="wr_body"></div>
    </div>
    <div ui-view="footer" class="sr_footer"></div>
</div>
</body>
</html>

templates/register.html
{% extends "base.html" %}

{% block header %}
    <div class="sr_margen">
        <div class="ih_cont">
            <div class="sr_logo">
                <a href="{% url "services:home" %}"><p>Servicioslibre<span>.com</span></p></a>
            </div>
            <div class="ih_nav">
                <ul>
                    <li><a href="#">¿Cómo funciona?</a></li>
                    <li><a href="#">¿Quieres brindar servicios?</a></li>
                    <li><a href="{% url 'services:request-service' %}">Solicitar servicio</a></li>
                </ul>
            </div>
            <div class="ih_sesion">
                <a class="sl-btn ihs_sign" href="{% url "account:register" %}">Regístrate</a>
                <a class="sl-btn ihs_login" href="{% url "account:login" %}">Inicia sesión</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="cont_log cont2-main">
        <div class="br_margen">
            <h1 class="title">Regístrate</h1>

            <div class="signuplike">
                <div class="slcont" id="serv">
                    <p>Como solicitante del servicio</p>
                </div>
                <div class="slcont" id="prov">
                    <p>Como proveedor de soluciones</p>
                </div>
            </div>
            <div id="servicio"
                    {% if second %}
                 style="display: none"
                    {% endif %}>
                <div class="login-container bubble">
                    {% if form.non_field_errors and not second %}
                        {{ form.non_field_errors }}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}

                        <p>
                            <i class="fa fa-user"></i>
                            <input type="text" name="first_name" required placeholder="¿Cómo te llamas?"/>
                        </p>

                        <p>
                            <i class="fa fa-envelope"></i>
                            <input type="email" name="email" required placeholder="¿Cuál es tu email?"/>
                        </p>

                        <p>
                            <i class="fa fa-lock"></i>
                            <input type="password" name="password" required placeholder="Contraseña"/>
                        </p>

                        <div class="controls">
                            <input name="second" class="sl-btn-2" type="submit" value="Crear una cuenta"/>
                        </div>
                    </form>
                </div>
                <h1 class="title">ó</h1>

                {#                <a href='{% url "social:begin" "facebook" %}' class="sl-btn-2 btn-blue btn-registro">Regístrate con#}
                {#                    <i class="fa fa-facebook-square"></i></a>#}

            </div>

            <div id="proveedor"
                    {% if not second %}
                 style="display: none"
                    {% endif %}>
                <div class="login-container bubble2">
                    {% if form.non_field_errors and second %}
                        {{ form.non_field_errors }}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="is_applicant" id="id_is_applicant" value="true">

                        <p>
                            <i class="fa fa-user"></i>
                            <input type="text" name="first_name" required placeholder="¿Cómo te llamas?"/>
                        </p>

                        <p>
                            <i class="fa fa-envelope"></i>
                            <input type="email" name="email" required placeholder="¿Cuál es tu email?"/>
                        </p>


                        <div class="as-p">
                            <i class="fa fa-suitcase"></i>

                            <div class="select-div">
                                <select name="category" id="category">
                                    <option value="" disabled selected>¿En que área te desenvuelves?</option>
                                    {% for category in categories %}
                                        <option name="category" value="{{ category.slug }}">{{ category.name }}</option>
                                    {% endfor %}


                                </select>
                            </div>
                        </div>

                        <p>
                            <i class="fa fa-lock"></i>
                            <input type="password" name="password" required placeholder="Contraseña"/>
                        </p>

                        <div class="controls">
                            <input name="second" class="sl-btn-2" type="submit" value="Crear una cuenta"/>
                        </div>
                    </form>
                </div>
            </div>

            <p class="loginq">¿Ya tienes una cuenta? <a href="{% url 'account:login' %}">Inicia sesión</a></p>
        </div>
    </div>
{% endblock %}